name: Feature request
description: Suggest an idea for the template
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: Describe the situation you are in, not just the solution you have in mind.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like the template to generate?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you considered?
